/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrlAlumnoMateria;
import controlador.CtrlAula;
import controlador.CtrlMateria;
import controlador.CtrlNotas;
import controlador.CtrlTurno;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.AlumnoMateria;
import modelo.Aula;
import modelo.Materia;
import modelo.Notas;
import modelo.Turno;

/**
 *
 * @author Leonel
 */
public class AlumnoNotas extends javax.swing.JInternalFrame {

    private Turno turno;
    private Aula aula;
    private AlumnoMateria alumnoMateria;
    private Notas nota;

    private CtrlAlumnoMateria ctrlAlumnoMateria;
    private CtrlAula ctrlAula;
    private CtrlTurno ctrlTurno;
    private CtrlNotas ctrlNotas;
    private CtrlMateria ctrlMateria;

    private List<Turno> listTurnos = new ArrayList<>();
    private List<Aula> listAulas = new ArrayList<>();
    private List<Materia> listMaterias = new ArrayList<>();
    private List<Alumno> listAlumnos = new ArrayList<>();

    private DefaultTableModel model;

    private int punto = 0, anio = 0;
    private Icon icono = new ImageIcon(getClass().getResource("/imagenes/modificar2.png"));

    public AlumnoNotas() {
        initComponents();

        ctrlAlumnoMateria = new CtrlAlumnoMateria();
        ctrlAula = new CtrlAula();
        ctrlNotas = new CtrlNotas();
        ctrlTurno = new CtrlTurno();
        ctrlMateria = new CtrlMateria();
        fechaNota.setDate(new Date());

        cargarComboTurno();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        paneListAlumno = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumno = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        paneAsigAula = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        cbxMateria = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        fechaNota = new com.toedter.calendar.JDateChooser();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cbxTurno = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        cbxAula = new javax.swing.JComboBox<>();

        setTitle("Asignar Notas");

        jPanel1.setBackground(new java.awt.Color(156, 156, 156));

        paneListAlumno.setBackground(new java.awt.Color(64, 207, 255));
        paneListAlumno.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Alumnos"));

        tblAlumno.setBorder(new javax.swing.border.MatteBorder(null));
        tblAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LEGAJO", "APELLIDO", "NOMBRE", "NOTAS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlumnoMouseClicked(evt);
            }
        });
        tblAlumno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblAlumnoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tblAlumnoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tblAlumno);
        if (tblAlumno.getColumnModel().getColumnCount() > 0) {
            tblAlumno.getColumnModel().getColumn(0).setResizable(false);
            tblAlumno.getColumnModel().getColumn(0).setPreferredWidth(33);
            tblAlumno.getColumnModel().getColumn(1).setResizable(false);
            tblAlumno.getColumnModel().getColumn(1).setPreferredWidth(120);
            tblAlumno.getColumnModel().getColumn(2).setResizable(false);
            tblAlumno.getColumnModel().getColumn(2).setPreferredWidth(120);
            tblAlumno.getColumnModel().getColumn(3).setResizable(false);
            tblAlumno.getColumnModel().getColumn(3).setPreferredWidth(5);
        }

        javax.swing.GroupLayout paneListAlumnoLayout = new javax.swing.GroupLayout(paneListAlumno);
        paneListAlumno.setLayout(paneListAlumnoLayout);
        paneListAlumnoLayout.setHorizontalGroup(
            paneListAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListAlumnoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        paneListAlumnoLayout.setVerticalGroup(
            paneListAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSalir.setBackground(new java.awt.Color(0, 51, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        paneAsigAula.setBackground(new java.awt.Color(64, 207, 255));
        paneAsigAula.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Alumnos"));

        jLabel19.setText("Materia");

        cbxMateria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMateriaItemStateChanged(evt);
            }
        });
        cbxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMateriaActionPerformed(evt);
            }
        });

        jLabel22.setText("Fecha");

        fechaNota.setBackground(new java.awt.Color(0, 152, 101));

        javax.swing.GroupLayout paneAsigAulaLayout = new javax.swing.GroupLayout(paneAsigAula);
        paneAsigAula.setLayout(paneAsigAulaLayout);
        paneAsigAulaLayout.setHorizontalGroup(
            paneAsigAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAsigAulaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaNota, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneAsigAulaLayout.setVerticalGroup(
            paneAsigAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneAsigAulaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(paneAsigAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneAsigAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(cbxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(new java.awt.Color(0, 51, 51));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(0, 51, 51));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar2.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 51, 51));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(64, 207, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Aulas"));

        jLabel23.setText("Turno");

        cbxTurno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTurnoItemStateChanged(evt);
            }
        });
        cbxTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTurnoActionPerformed(evt);
            }
        });

        jLabel24.setText("Aula");

        cbxAula.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxAulaItemStateChanged(evt);
            }
        });
        cbxAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(7, 7, 7)
                .addComponent(cbxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxAula, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cbxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(cbxAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalir)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(paneListAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paneAsigAula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(paneAsigAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(paneListAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnModificar)
                        .addComponent(btnEliminar))
                    .addComponent(btnSalir))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMateriaActionPerformed

    }//GEN-LAST:event_cbxMateriaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (fechaNota.getDate() != null) {
            for (int i = 0; i < listAlumnos.size(); i++) {
                nota = new Notas();
                alumnoMateria = new AlumnoMateria();
                alumnoMateria.setAlumno(listAlumnos.get(i));
                alumnoMateria.setAula(listAulas.get(cbxAula.getSelectedIndex()));
                alumnoMateria.setMateria(listMaterias.get(cbxMateria.getSelectedIndex()));
                alumnoMateria = ctrlAlumnoMateria.leerAlumno(alumnoMateria);
                nota.setAlumnoMateria(alumnoMateria);
                nota.setNota(Float.valueOf(tblAlumno.getValueAt(i, 3).toString()));
                nota.setFecha(fechaNota.getDate());
                if (nota.getNota() > 0.0) {
                    ctrlNotas.crear(nota);
                }
            }
            limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar la Fecha", "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cbxTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxTurnoActionPerformed

    private void cbxAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAulaActionPerformed

    private void cbxTurnoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTurnoItemStateChanged
        if (cbxTurno.getItemCount() > 0) {
            cbxAula.removeAllItems();
            cargarComboAula();
        }

    }//GEN-LAST:event_cbxTurnoItemStateChanged

    private void cbxAulaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxAulaItemStateChanged
        cbxMateria.removeAllItems();
        if (cbxAula.getItemCount() > 0) {
            cargarComboMaterias();

        }

    }//GEN-LAST:event_cbxAulaItemStateChanged

    private void tblAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnoMouseClicked
        punto = tblAlumno.rowAtPoint(evt.getPoint());
        String nombre = (String) JOptionPane.showInputDialog(null, "Ingresa la nota", "Notas", JOptionPane.INFORMATION_MESSAGE, icono, null, "");

        if (nombre != null) {
            float nota = Float.parseFloat(nombre);
            if (nota > 0 && nota <= 10) {
                tblAlumno.setValueAt(nota, punto, 3);
            } else {
                JOptionPane.showMessageDialog(this, "La nota debe estar entre 1 y 10");
            }
        }


    }//GEN-LAST:event_tblAlumnoMouseClicked

    private void tblAlumnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAlumnoKeyPressed

    }//GEN-LAST:event_tblAlumnoKeyPressed

    private void cbxMateriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMateriaItemStateChanged
        if (cbxMateria.getItemCount() > 0) {
            cargarTablaAlumnos();
        }

    }//GEN-LAST:event_cbxMateriaItemStateChanged

    private void tblAlumnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblAlumnoKeyTyped

//        System.out.println(tblAlumno.getValueAt(punto, 3).toString());
//        if (Float.parseFloat(tblAlumno.getValueAt(punto, 3).toString()) < 1
//                || Float.parseFloat(tblAlumno.getValueAt(punto, 3).toString()) > 10) {
//            JOptionPane.showMessageDialog(this, "Solo puede ingresar notas desde 1 a 10");
//
//        }
        String texto = tblAlumno.getValueAt(punto, 3).toString();
        if (texto.length() >= 1) {
            evt.consume();
        }
    }//GEN-LAST:event_tblAlumnoKeyTyped
    private void validar() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    public static javax.swing.JComboBox<String> cbxAula;
    public static javax.swing.JComboBox<String> cbxMateria;
    public static javax.swing.JComboBox<String> cbxTurno;
    private com.toedter.calendar.JDateChooser fechaNota;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel paneAsigAula;
    private javax.swing.JPanel paneListAlumno;
    private javax.swing.JTable tblAlumno;
    // End of variables declaration//GEN-END:variables

    private void cargarComboAula() {
        listAulas = ctrlAula.leer(listTurnos.get(cbxTurno.getSelectedIndex()).getIdTurno());
        for (int i = 0; i < listAulas.size(); i++) {
            cbxAula.addItem("Curso: " + listAulas.get(i).getCurso().getCurso()
                    + " | Div: " + listAulas.get(i).getDivision().getDivision());
        }
    }

    private void cargarComboTurno() {
        listTurnos = ctrlTurno.leerTurno();
        for (int i = 0; i < listTurnos.size(); i++) {
            cbxTurno.addItem(listTurnos.get(i).getTurno());
        }
    }

    private void cargarComboMaterias() {
        alumnoMateria = new AlumnoMateria();

        alumnoMateria.setAula(listAulas.get(cbxAula.getSelectedIndex()));
        //listMaterias = ctrlAlumnoMateria.leerAulaMateria(alumnoMateria);
        String curso = "" + alumnoMateria.getAula().getCurso().getCurso().charAt(0);
        listMaterias = ctrlMateria.leerAnio(Integer.parseInt(curso));
        for (int i = 0; i < listMaterias.size(); i++) {
            // System.err.println(i);
            cbxMateria.addItem(listMaterias.get(i).getMateria());
        }
    }

    private void cargarTablaAlumnos() {
        model = (DefaultTableModel) tblAlumno.getModel();
        model.setRowCount(0);
        alumnoMateria = new AlumnoMateria();
        alumnoMateria.setMateria(listMaterias.get(cbxMateria.getSelectedIndex()));
        alumnoMateria.setAula(listAulas.get(cbxAula.getSelectedIndex()));
        listAlumnos = ctrlAlumnoMateria.leerAulaAlumno(alumnoMateria);
        Object[] fila = new Object[4];
        for (int i = 0; i < listAlumnos.size(); i++) {
            fila[0] = listAlumnos.get(i).getPersonal().getLegajo();
            fila[1] = listAlumnos.get(i).getPersonal().getApellido();
            fila[2] = listAlumnos.get(i).getPersonal().getNombre();
            fila[3] = 0.0;
            model.addRow(fila);
        }
        tblAlumno.setModel(model);
    }

    private void limpiar() {
        cbxTurno.setSelectedIndex(0);
        cbxTurno.removeAllItems();
        cargarComboTurno();
        fechaNota.setDate(new Date());
    }
}
