/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrlEstadoCivil;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import modelo.EstadoCivil;

/**
 *
 * @author Leonel
 */
public class EstadosCiviles extends javax.swing.JInternalFrame {
    CtrlEstadoCivil ctrlEstadoCivil = new CtrlEstadoCivil();
    EstadoCivil estadoCivil = new EstadoCivil();
    DefaultTableModel modeloTabla = new DefaultTableModel();
    List<EstadoCivil> listaEstadosCiviles = new ArrayList();
    int idEstadoCivil;
    /**
     * Creates new form EstadosCiviles
     */
    public EstadosCiviles() {
        initComponents();
        cargarTabla();
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }
    
    public void cargarTabla()
    {
        modeloTabla = (DefaultTableModel) tblEstadosCiviles.getModel();
        String[] fila = new String[1];
        modeloTabla.setRowCount(0);
        listaEstadosCiviles = ctrlEstadoCivil.leerTodos();
        
        for(int i=0; i< listaEstadosCiviles.size(); i++){
            fila[0] = listaEstadosCiviles.get(i).getEstadoCivil();
            modeloTabla.addRow(fila);
        }
        tblEstadosCiviles.setModel(modeloTabla);
    }
    
    public void limpiar()
    {
        cargarTabla();
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        txtEstadoCivil.setText("");
        idEstadoCivil = 0;
        txtEstadoCivil.requestFocus();
    }
    
    public Boolean validar()
    {
        txtEstadoCivil.setBorder(new JTextField().getBorder());
        Boolean validar = false;
        if(txtEstadoCivil.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar Estado Civil");
            txtEstadoCivil.setBorder(new LineBorder(Color.RED, 2));
            txtEstadoCivil.requestFocus();
        }else{
            validar = true;
        }
        return validar;
    }
    
    public void crearEstadoCivil()
    {
        if(validar() == true)
        {
            estadoCivil = ctrlEstadoCivil.leerEstadoCivil(txtEstadoCivil.getText().toUpperCase());
            if(estadoCivil!=null)
            {
                JOptionPane.showMessageDialog(null, "Este Estado Civil ya existe");
                txtEstadoCivil.requestFocus();
            }else{
                estadoCivil = new EstadoCivil();
                estadoCivil.setEstadoCivil(txtEstadoCivil.getText().toUpperCase());
                ctrlEstadoCivil.crearEstadoCivil(estadoCivil);
                limpiar();
            }
        }
    }
    
    public void modificarEstadoCivil()
    {
        if(validar() == true)
        {
            estadoCivil = ctrlEstadoCivil.leerEstadoCivil(txtEstadoCivil.getText().toUpperCase());
            if(estadoCivil!=null)
            {
                JOptionPane.showMessageDialog(null, "Este Estado Civil ya existe");
                txtEstadoCivil.requestFocus();
            }else{
                estadoCivil = new EstadoCivil();
                estadoCivil.setIdEstadoCivil(idEstadoCivil);
                estadoCivil.setEstadoCivil(txtEstadoCivil.getText().toUpperCase());
                ctrlEstadoCivil.modificarEstadoCivil(estadoCivil);
                limpiar();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstadosCiviles = new javax.swing.JTable();

        setTitle("Estados Civiles");

        jPanel1.setBackground(new java.awt.Color(0, 152, 101));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estadoCivil.png"))); // NOI18N
        jLabel1.setText("Estado Civil");

        txtEstadoCivil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoCivilKeyTyped(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 51, 51));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(0, 51, 51));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar2.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 51, 51));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 51, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tblEstadosCiviles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ESTADOS CIVILES"
            }
        ));
        tblEstadosCiviles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblEstadosCivilesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblEstadosCiviles);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstadoCivil)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        crearEstadoCivil();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificarEstadoCivil();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ctrlEstadoCivil.eliminarEstadoCivil(estadoCivil);
        limpiar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblEstadosCivilesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstadosCivilesMousePressed
        int FilaSelec = tblEstadosCiviles.getSelectedRow();
        txtEstadoCivil.setText(tblEstadosCiviles.getValueAt(FilaSelec, 0).toString());
        estadoCivil = ctrlEstadoCivil.leerEstadoCivil(txtEstadoCivil.getText());
        idEstadoCivil = estadoCivil.getIdEstadoCivil();
        txtEstadoCivil.requestFocus();
        btnGuardar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tblEstadosCivilesMousePressed

    private void txtEstadoCivilKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoCivilKeyTyped
        if(txtEstadoCivil.getText().length() == 45){
            evt.consume();
        }
    }//GEN-LAST:event_txtEstadoCivilKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEstadosCiviles;
    private javax.swing.JTextField txtEstadoCivil;
    // End of variables declaration//GEN-END:variables
}
