/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrlMateria;
import controlador.CtrlPlanEstudio;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import modelo.Materia;
import modelo.PlanEstudio;

/**
 *
 * @author Leonel
 */
public class Materias extends javax.swing.JInternalFrame {
    CtrlMateria ctrlMateria = new CtrlMateria();
    CtrlPlanEstudio ctrlPlanEstudio = new CtrlPlanEstudio();
    Materia materia = new Materia();
    PlanEstudio planEstudio = new PlanEstudio();
    List<PlanEstudio> listaPlanEstudio = new ArrayList();
    DefaultTableModel modeloTabla = new DefaultTableModel();
    List<Materia> listaMaterias = new ArrayList();
    int idMateria;
    String nombreMateria;
    int año = 1;
    /**
     * Creates new form Materias
     */
    public Materias() {
        initComponents();
        cargarTabla();
        cargarCbxPlanEstudio();
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    public void cargarCbxPlanEstudio()
    {
        listaPlanEstudio = ctrlPlanEstudio.leerTodos();
        cbxPlanEstudio.removeAllItems();
        for(int i = 0; i<listaPlanEstudio.size(); i++)
        {
            cbxPlanEstudio.addItem(listaPlanEstudio.get(i).getTitulo());
        }
    }
    
    public void cargarTabla()
    {
        modeloTabla = (DefaultTableModel) tblMaterias.getModel();
        String[] fila = new String[3];
        modeloTabla.setRowCount(0);
        listaMaterias = ctrlMateria.leerTodos();
        
        for(int i=0; i< listaMaterias.size(); i++){
            fila[0] = listaMaterias.get(i).getMateria();
            fila[1] = listaMaterias.get(i).getPlanEstudio().getTitulo();
            fila[2] = String.valueOf(listaMaterias.get(i).getAño());
            modeloTabla.addRow(fila);
        }
        tblMaterias.setModel(modeloTabla);
    }
    
    public void limpiar()
    {
        cargarTabla();
        cargarCbxPlanEstudio();
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        txtMateria.setText("");
        idMateria = 0;
        cbxPlanEstudio.setSelectedIndex(0);
        cbxAño.setSelectedIndex(0);
        txtMateria.requestFocus();
    }
    
    public Boolean validar()
    {
        txtMateria.setBorder(new JTextField().getBorder());
        Boolean validar = false;
        if(txtMateria.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar Materia");
            txtMateria.setBorder(new LineBorder(Color.RED, 2));
            txtMateria.requestFocus();
        }else{
            validar = true;
        }
        return validar;
    }
    
    public void crearMateria()
    {
        if(validar() == true)
        {
            materia = ctrlMateria.leerMateria(txtMateria.getText().toUpperCase(), año);
            if(materia!=null)
            {
                JOptionPane.showMessageDialog(null, "Esta Materia ya existe");
                txtMateria.requestFocus();
            }else{
                materia = new Materia();
                materia.setMateria(txtMateria.getText().toUpperCase());
                materia.setPlanEstudio(ctrlPlanEstudio.leerPlanEstudio(cbxPlanEstudio.getSelectedItem().toString()));
                materia.setAño(año);
                ctrlMateria.crearMateria(materia);
                limpiar();
            }
        }
    }
    
    public void modificarMateria()
    {
        if(validar() == true)
        {
            materia = ctrlMateria.leerMateria(txtMateria.getText().toUpperCase(), año);
            if(materia!=null && !txtMateria.getText().equalsIgnoreCase(nombreMateria))
            {
                JOptionPane.showMessageDialog(null, "Esta Materia ya existe");
                txtMateria.requestFocus();
            }else{
                materia = new Materia();
                materia.setIdMateria(idMateria);
                materia.setMateria(txtMateria.getText().toUpperCase());
                materia.setPlanEstudio(ctrlPlanEstudio.leerPlanEstudio(cbxPlanEstudio.getSelectedItem().toString()));
                materia.setAño(año);
                ctrlMateria.modificarMateria(materia);
                limpiar();
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterias = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxPlanEstudio = new javax.swing.JComboBox<>();
        cbxAño = new javax.swing.JComboBox<>();

        setTitle("Materias");

        jPanel1.setBackground(new java.awt.Color(64, 207, 255));

        jLabel1.setText("Materia");

        txtMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMateriaKeyTyped(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 51, 51));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(0, 51, 51));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar2.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 51, 51));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 51, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tblMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MATERIAS", "PLAN DE ESTUDIO", "AÑO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblMateriasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaterias);
        if (tblMaterias.getColumnModel().getColumnCount() > 0) {
            tblMaterias.getColumnModel().getColumn(0).setResizable(false);
        }

        jLabel2.setText("Plan de Estudio");

        jLabel3.setText("Año");

        cbxAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 ° ", "2 ° ", "3 ° ", "4 ° ", "5 ° " }));
        cbxAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAñoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMateria))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxPlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxAño, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSalir)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxPlanEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        crearMateria();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int confirmar,respuesta;
        confirmar = JOptionPane.YES_NO_OPTION;
        respuesta = JOptionPane.showConfirmDialog(null,"¿Desea modificar la materia?","Modificar",confirmar);
        if (respuesta == 0 )
        {
            modificarMateria();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int confirmar,respuesta;
        confirmar = JOptionPane.YES_NO_OPTION;
        respuesta = JOptionPane.showConfirmDialog(null,"¿Desea eliminar la materia?","Eliminar",confirmar);
        if (respuesta == 0 )
        {
            ctrlMateria.eliminarMateria(materia);
            limpiar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblMateriasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMateriasMousePressed
        int FilaSelec = tblMaterias.getSelectedRow();
        txtMateria.setText(tblMaterias.getValueAt(FilaSelec, 0).toString());
        cbxPlanEstudio.setSelectedItem(tblMaterias.getValueAt(FilaSelec, 1));
        cbxAño.setSelectedItem(tblMaterias.getValueAt(FilaSelec, 2)+" ° ");
        materia = ctrlMateria.leerMateria(txtMateria.getText(), año);
        idMateria = materia.getIdMateria();
        nombreMateria = txtMateria.getText();
        txtMateria.requestFocus();
        btnGuardar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tblMateriasMousePressed

    private void txtMateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMateriaKeyTyped
        if(txtMateria.getText().length() == 45){
            evt.consume();
        }
    }//GEN-LAST:event_txtMateriaKeyTyped

    private void cbxAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAñoActionPerformed
        String añoMateria = (String) cbxAño.getSelectedItem();
        String[] parts = añoMateria.split(" ");
        año = Integer.valueOf(parts[0]);
    }//GEN-LAST:event_cbxAñoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxAño;
    private javax.swing.JComboBox<String> cbxPlanEstudio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMaterias;
    private javax.swing.JTextField txtMateria;
    // End of variables declaration//GEN-END:variables
}
