/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CtrlSancion;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Sancion;

/**
 *
 * @author Kevin
 */
public class Sanciones extends javax.swing.JInternalFrame {

    private DefaultTableModel model = new DefaultTableModel();
    private Sancion sancion;
    private CtrlSancion ctrlSancion;
    private List<Sancion> sancione = new ArrayList();
    private boolean modif = false;
    private int punto = 0;

    /**
     * Creates new form NuevoCargo
     */
    public Sanciones() {
        initComponents();
        btnEliminar.setEnabled(false);
        ctrlSancion = new CtrlSancion();
        cargarTableSancion();
        txtSancion.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        lblSancion = new javax.swing.JLabel();
        txtSancion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSancion = new javax.swing.JTable();

        setTitle("Nueva Sancion");

        jPanel1.setBackground(new java.awt.Color(64, 207, 255));

        btnEliminar.setBackground(new java.awt.Color(0, 51, 51));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblSancion.setText("Sancion");

        txtSancion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSancionKeyTyped(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 51, 51));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(0, 51, 51));
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tblSancion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sancion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSancionMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblSancionMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblSancion);
        if (tblSancion.getColumnModel().getColumnCount() > 0) {
            tblSancion.getColumnModel().getColumn(0).setResizable(false);
            tblSancion.getColumnModel().getColumn(0).setPreferredWidth(120);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSancion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSancion, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(btnGuardar)
                        .addGap(12, 12, 12)
                        .addComponent(btnEliminar)
                        .addGap(12, 12, 12)
                        .addComponent(btnSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSancion)
                    .addComponent(txtSancion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnSalir)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSancionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSancionKeyTyped

    }//GEN-LAST:event_txtSancionKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (!txtSancion.getText().isEmpty()) {
            sancion = new Sancion();
            sancion.setSancion(txtSancion.getText());
            if (modif == true) {
                sancion.setIdSancion(sancione.get(punto).getIdSancion());
                ctrlSancion.modificar(sancion);
            } else {
                ctrlSancion.crear(sancion);
            }
            JOptionPane.showMessageDialog(this, "Guardado");
            limpiar();
        }else{
            JOptionPane.showMessageDialog(this, "Complete el cuadro de Texto Sanción");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tblSancionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSancionMousePressed

    }//GEN-LAST:event_tblSancionMousePressed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        sancion = new Sancion();
        sancion.setIdSancion(sancione.get(punto).getIdSancion());

        int confirmar = JOptionPane.YES_NO_OPTION;
        int respuesta = JOptionPane.showConfirmDialog(null, "<html>¿Está seguro que quiere eliminar esta Sanción:<br><b> "
                + sancione.get(punto).getSancion() + "</b></br>?</html>", "Advertencia", confirmar, JOptionPane.WARNING_MESSAGE);
        if (respuesta == 0) {
            ctrlSancion.eliminar(sancion);
            JOptionPane.showMessageDialog(null, "ELIMINADO CON EXITO");
            limpiar();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblSancionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSancionMouseClicked
        punto = tblSancion.rowAtPoint(evt.getPoint());
        txtSancion.setText(sancione.get(punto).getSancion());
        modif = true;
        btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tblSancionMouseClicked
    private void cargarTableSancion() {
        model = (DefaultTableModel) tblSancion.getModel();
        model.setRowCount(0);
        Object[] fila = new Object[1];
        sancione = ctrlSancion.leerTodos();

        for (int i = 0; i < sancione.size(); i++) {
            fila[0] = sancione.get(i).getSancion();
            model.addRow(fila);
        }
        tblSancion.setModel(model);
    }

    private void limpiar() {
        txtSancion.setText(null);
        sancione.clear();
        cargarTableSancion();
        modif = false;
        txtSancion.requestFocus();
        btnEliminar.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSancion;
    private javax.swing.JTable tblSancion;
    private javax.swing.JTextField txtSancion;
    // End of variables declaration//GEN-END:variables
}
